# Generated by Django 2.0.1 on 2018-06-02 02:09

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=5)),
                ('birthDate', models.DateField(verbose_name=('%d-%m-%Y', '%Y-%m-%d'))),
                ('password', models.CharField(max_length=200)),
                ('phone_number', phone_field.models.PhoneField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('countryCode', django_countries.fields.CountryField(max_length=2)),
                ('picture_path', models.CharField(max_length=500)),
            ],
        ),
    ]
